version: "3.9"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 65432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: home_school
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local
